[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
(
    ^/mission_planner/
  | ^/src/new_control_station/libs/
  | ^/src/controls/__pycache__/
  | ^/_build/
  | ^/build/
  | ^\.venv/
  | .*\.pyc$
)
'''

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20
