site_name: 'Nebula Docs'
site_description: 'Nebula 2025 Drone System Documentation'
site_author: 'Amar Jay'
site_url: 'https://nebula.amarjay.com'

copyright: |
  &copy; Amar Jay

docs_dir: docs/

repo_name: amar-jay/nubula
repo_url: https://github.com/AmarJay/nubula

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/img/favicons/logo.png'
  logo: 'assets/img/favicons/logo.png'
  icon:
    repo: simple/codeberg
    admonition:
      note: octicons/pencil-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/comment-16
    tag:
      mc: material/minecraft
      spigot: fontawesome/solid/faucet-drip
      paypal: fontawesome/brands/paypal
      java: fontawesome/brands/java
      discord: fontawesome/brands/discord
      mastodon: fontawesome/brands/mastodon
      twitter: fontawesome/brands/twitter
      gitea: simple/gitea
      forgejo: simple/forgejo
  palette:
    scheme: 'slate'
    primary: 'custom'
    accent: 'blue'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.annotate
    - content.tooltips

extra_css:
- assets/css/extra.css

extra_javascript:
- assets/js/expansion_stats.js
- assets/js/timeago.min.js
- assets/js/timeago_mkdocs_material.js

watch:
  - theme

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Türkçe
      link: /tr/
      lang: tr
  social:
    - icon: 'simple/x'
      link: 'https://x.com/@_amarjay'
  tags:
    Minecraft: mc
    SpigotMC: spigot
    PayPal: paypal
    Java: java
    Discord: discord
    Mastodon: mastodon
    Twitter: twitter
    Gitea: gitea
    Forgejo: forgejo
  mastodon:
    host: swiss.social
    user: andre_601
  share:
    - link: 'https://mastodonshare.com/?url={url}&text={title}'
      icon: 'simple/mastodon'
      title: 'Toot Post on Mastodon!'
      class: 'md-button__social--mastodon'
    - link: 'https://bsky.app/intent/compose?text={title}%0A{url}'
      icon: 'simple/bluesky'
      title: 'Share Post on Bluesky!'
      class: 'md-button__social--bluesky'

nav:
  - Main Page: index.md
  - GCS:
    - gcs/index.md
  - Comms:
    - comms/index.md
  - Vision:
    - vision/index.md
  - Simulation:
    - simulation/index.md
    - Formatter:
      - simulation/formatter/index.md
      - Numbers:
        - simulation/formatter/format.md
        - simulation/formatter/from-to.md
        - simulation/formatter/round.md
        - simulation/formatter/shorten.md
        - simulation/formatter/time.md
      - Text:
        - simulation/formatter/capitalize.md
        - simulation/formatter/length.md
        - simulation/formatter/lowercase.md
        - simulation/formatter/replace.md
        - simulation/formatter/substring.md
        - simulation/formatter/uppercase.md
    - Math:
      - simulation/math/index.md
      - simulation/math/placeholder.md
    - RandomColor:
      - simulation/randomcolor/index.md
      - Placeholders:
        - simulation/randomcolor/all.md
        - simulation/randomcolor/color.md
        - simulation/randomcolor/combined.md
        - simulation/randomcolor/format.md
        - simulation/randomcolor/selected.md
    - Shortcut:
      - simulation/shortcut/index.md
      - simulation/shortcut/placeholder.md
not_in_nav: |
  luckperms.md

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      authors: true
      post_date_format: 'dd. MMM yyyy'
      post_url_date_format: yyyy
      post_url_format: '{date}/{file}'
      archive: true
      archive_url_format: '{date}'
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      draft_if_future_date: true
  - rss:
      match_path: blog/posts/*
      categories:
        - categories
        - tags
      comments_path: '#__comments'
  - tags:
  - git-revision-date-localized:
      type: custom
      timezone: Europe/Zurich
      locale: en
      custom_format: '%d. %B %Y'
      exclude:
        - blog/index.md
        - blog/posts/index.md
        - blog/posts/tags.md
  - glightbox
  - meta

markdown_extensions:
  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
      PLACE_MARKER: "<!-- Footnotes -->"
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: 'theme/snippets'
  - pymdownx.superfences:
  - pymdownx.tilde:
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - download
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: true

hooks:
  - theme/hooks/footnotes.py